{{- if .Values.pdb.enabled -}}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "binderhub.fullname" . }}
  labels:
    {{- include "binderhub.matchLabels" . | nindent 4 }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not (.Values.pdb.maxUnavailable | typeIs "<nil>") }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  {{- if not (.Values.pdb.minAvailable | typeIs "<nil>") }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "binderhub.matchLabels" . | nindent 6 }}
{{- end }}
