apiVersion: v1
kind: Service
metadata:
  name: {{ include "binderhub.fullname" . }}
  annotations: {{ .Values.service.annotations | toJson }}
  labels: {{ .Values.service.labels | toJson }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  selector:
    {{- include "binderhub.matchLabels" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
